### ISSUE TITLE
IAM Role support in bang for aws?

### ISSUE THREAD

**Issue by creftos** [fr33jc/bang#24]
I've been having trouble figuring out how to add IAM roles to AWS server definition files. I see an example in a rightscale server definition file that does something like:

```
rightscale:
  cloud_specific_attributes:
      iam_instance_profile: <instance profile name>
```

But I can't seem to be able to do the same thing for aws. 

Has this been implemented yet, or is this still a todo for bang?

**Comment by fr33jc** [comment]
Hey @creftos - have a look at the minimal server example in bang/examples/aws

**Comment by creftos** [comment]
Doi! Dunno how I missed that. Thanks!
